set(_AMENT_PACKAGE_NAME "robocon_desktop")
set(robocon_desktop_VERSION "0.0.0")
set(robocon_desktop_MAINTAINER "tong <samnangkong499@gmail.com>")
set(robocon_desktop_BUILD_DEPENDS )
set(robocon_desktop_BUILDTOOL_DEPENDS "ament_cmake")
set(robocon_desktop_BUILD_EXPORT_DEPENDS )
set(robocon_desktop_BUILDTOOL_EXPORT_DEPENDS )
set(robocon_desktop_EXEC_DEPENDS )
set(robocon_desktop_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(robocon_desktop_GROUP_DEPENDS )
set(robocon_desktop_MEMBER_OF_GROUPS )
set(robocon_desktop_DEPRECATED "")
set(robocon_desktop_EXPORT_TAGS)
list(APPEND robocon_desktop_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
